// Mocks generated by Mockito 5.0.8 from annotations
// in flutter_dispose_scope/test/disposed_extensions/decoration_image_painter_disposed_test.dart.
// Do not manually edit this file.

import 'dart:ui' as _i3;

import 'package:flutter/src/painting/decoration_image.dart' as _i2;
import 'package:flutter/src/painting/image_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [DecorationImagePainter].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecorationImagePainter extends _i1.Mock
    implements _i2.DecorationImagePainter {
  MockDecorationImagePainter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void paint(_i3.Canvas? canvas, _i3.Rect? rect, _i3.Path? clipPath,
          _i4.ImageConfiguration? configuration) =>
      super.noSuchMethod(
          Invocation.method(#paint, [canvas, rect, clipPath, configuration]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  String toString() =>
      (super.noSuchMethod(Invocation.method(#toString, []), returnValue: '')
          as String);
}
