// Mocks generated by Mockito 5.0.8 from annotations
// in flutter_dispose_scope/test/disposed_extensions/disposable_build_context_disposed_test.dart.
// Do not manually edit this file.

import 'package:flutter/src/widgets/disposable_build_context.dart' as _i3;
import 'package:flutter/src/widgets/framework.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [DisposableBuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisposableBuildContext<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.Mock implements _i3.DisposableBuildContext<T> {
  MockDisposableBuildContext() {
    _i2.throwOnMissingStub(this);
  }

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
