// Mocks generated by Mockito 5.0.8 from annotations
// in flutter_dispose_scope/test/disposed_extensions/semantics_handle_disposed_test.dart.
// Do not manually edit this file.

import 'package:flutter/src/rendering/object.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [SemanticsHandle].
///
/// See the documentation for Mockito's code generation for more information.
class MockSemanticsHandle extends _i1.Mock implements _i2.SemanticsHandle {
  MockSemanticsHandle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
