// Mocks generated by Mockito 5.0.15 from annotations
// in dispose_scope/test/dispose_scope_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'disposable.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Disposable].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisposable extends _i1.Mock implements _i2.Disposable {
  MockDisposable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
