// Mocks generated by Mockito 5.0.8 from annotations
// in dispose_scope/test/disposed_extensions/connection_task_disposed_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ConnectionTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionTask<S> extends _i1.Mock implements _i2.ConnectionTask<S> {
  MockConnectionTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<S> get socket => (super.noSuchMethod(Invocation.getter(#socket),
      returnValue: Future<S>.value(null)) as _i3.Future<S>);
  @override
  void cancel() => super.noSuchMethod(Invocation.method(#cancel, []),
      returnValueForMissingStub: null);
}
