// Mocks generated by Mockito 5.0.15 from annotations
// in dispose_scope/test/disposed_extensions/dispose_scope_disposed_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dispose_scope/src/dispose.dart' as _i3;
import 'package:dispose_scope/src/dispose_scope.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [DisposeScope].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisposeScope extends _i1.Mock implements _i2.DisposeScope {
  MockDisposeScope() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addDispose(_i3.Dispose? dispose) =>
      super.noSuchMethod(Invocation.method(#addDispose, [dispose]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
