name: flutter_dispose_scope
description: Package supporting flutter types for dispose_scope.
version: 2.0.0
repository: https://github.com/RobertOdrowaz/dispose-scope/tree/master/packages/flutter_dispose_scope
issue_tracker: https://github.com/RobertOdrowaz/dispose-scope/issues
homepage: https://github.com/RobertOdrowaz/dispose-scope

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dispose_scope: ^2.0.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.8
